server:
  net: 1
  http_port: ":9092"
  cron_spec: "0 30 */1 * * ?" # refund regular
  remote_sign_api_url: ""
business_ids: # Link to business callback when order payment and refund are completed
  "das-register-svr": "http://127.0.0.1:8119/v1/unipay/notice"
notify:
  lark_error_key: ""
  stripe_key: ""
db:
  mysql:
    addr: "docker.for.mac.localhost:3306" #"127.0.0.1:3306"
    user: "root"
    password: "12345678"
    db_name: "unipay_db"
chain:
  ckb:
    refund: true # do refund
    switch: true # start tx parse
    node: ""
    addr_map: # address & private for refund
      "": ""
  eth:
    refund: true
    switch: true
    node: "http://127.0.0.1:8585"
    refund_add_fee: 1.1
    addr_map: # address & private
      "": ""
  tron:
    refund: true
    switch: true
    node: "127.0.0.1:50051"
    refund_add_fee: 1.1
    addr_map: # address & private
      "": ""
  bsc:
    refund: true
    switch: true
    node: ""
    refund_add_fee: 1.1
    addr_map: # address & private
      "": ""
  polygon:
    refund: true
    switch: true
    node: "https://polygon-rpc.com"
    refund_add_fee: 1.1
    addr_map: # address & private
      "": ""
  doge:
    refund: true
    switch: true
    node: ""
    user: ""
    password: ""
    addr_map: # address & private
      "": ""