server:
  name: "unipay"
  net: 2
  http_port: ":9092"
  cron_spec: "0 30 */1 * * ?" # refund regular
  remote_sign_api_url: ""
  prometheus_push_gateway: ""
business_ids:
  "das-register-svr": "url/v1/unipay/notice"
  "auto-sub-account": "url/v1/unipay/notice"
  "dp-svr": ""
notify:
  lark_error_key: ""
  lark_das_info_key: ""
  stripe_key: ""
db:
  mysql:
    addr: ""
    user: ""
    password: ""
    db_name: ""
chain:
  dp:
    refund: true
    switch: true
    node: ""
    current_block_number: 0
    transfer_whitelist: ""
    transfer_whitelist_private: ""
    refund_url: ""
  ckb:
    refund: true # do refund
    switch: true # start tx parse
    node: ""
    balance_check_map:
    addr_map:
      "ckt1****": ""
      "ckt2****": ""

  eth:
    refund: true
    switch: true
    node: ""
    refund_add_fee: 1.5
    addr_map:
      "0x04A***": ""
  tron:
    refund: true
    switch: true
    node: ""
    refund_add_fee: 1.2
    addr_map:
      "TEfv***": ""

  bsc:
    refund: true
    switch: true
    node: ""
    refund_add_fee: 1.2
    addr_map:
      "0x04A5***": ""
  polygon:
    refund: true
    switch: true
    node: ""
    refund_add_fee: 1.2
    addr_map:
      "0x04A***": ""

  doge:
    tx_chan_num: 10
    refund: true
    switch: true
    node: ""
    user: "" #"tokenpocket"
    password: "" #"tokenpocket"
    addr_map:
      "DQaRQ***": ""

  btc:
    utxo_api_url: ""
    utxo_api_key: ""
    refund: true
    switch: true
    node: ""
    user: "root"
    password: "root"
    addr_map:
      "tb1q****": ""
  stripe:
    refund: true
    switch: true
    key: ""
    endpoint_secret: ""
    webhooks_addr: ":"
    large_amount: 10
