name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  cd:
    runs-on: sg
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download Artifct
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: CI
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
          run_number: ${{ github.event.workflow_run.run_number }}
          name: unipay
      - name: Stop Service
        run: ssh root@backendtest 'supervisorctl stop unipay_svr && supervisorctl stop refund_svr'
      - name: Rsync
        run: rsync -a unipay_svr root@backendtest:/mnt/das/server/unipay/unipay_svr
      - name: Rsync
        run: rsync -a refund_svr root@backendtest:/mnt/das/server/unipay/refund_svr
      - name: Restart Service
        run: ssh root@backendtest 'chmod +x /mnt/das/server/unipay/unipay_svr && supervisorctl start unipay_svr'
      - name: Restart Service
        run: ssh root@backendtest 'chmod +x /mnt/das/server/unipay/refund_svr && supervisorctl start refund_svr'